name: phonecodes
description: This package provides a list of Countries with their name, ISO code, Dial code, Flag.
version: 0.0.0
repository: https://github.com/HeySreelal/phonecodes

environment:
  sdk: ^3.0.4

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
