name: phonecodes
description: This package provides a list of Countries with their name, ISO code, Dial code, Flag and Currency
version: 0.0.2
repository: https://github.com/HeySreelal/phonecodes
topics:
  - Country Codes
  - Countries
  - Currency
  - Dial Codes
  - Flags

environment:
  sdk: ^3.0.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
